
#welcome page
welcome_titlepane=Bienvenue sur {0}
welcome_h3=Bienvenue sur {0}
welcome_text=Bienvenue
welcome.entite.list=Entit\u00e9s
back.welcome=Retour \u00e0 la page d'accueil

# actions
create=Cr\u00e9er
edit=Modifier
delete=Supprimer
save=Enregistrer
save.ok=Enregistrement effectu\u00e9
list=Liste
back=Retour
cancel=Annuler
reset=R\u00e9initialiser

# errors
error=Erreur: {0}
error.with.cause=Erreur: {0}, cause: {1}
already.exists=Cette entit\u00e9 existe d\u00e9j\u00e0

#foreach( $entity in $selectedEntities )
# ${entity.name.toLowerCase()}
${entity.name.toLowerCase()}=${entity.name}
${entity.name.toLowerCase()}.list=${entity.name.toLowerCase()}s
#foreach( $field in ${entity.attributes} )
${entity.name.toLowerCase()}.${field.formatedName(0)}=${field.label}
#if( $field.isKeyElement() || $field.isNotNull() )
NotNull.${entity.name.toLowerCase()}.${field.formatedName(0)}=Le champ ${field.label} doit \u00eatre renseign\u00e9
#end
#end
#foreach( $link in $entity.selectedLinks )
#if( !$link.isCardinalityManyToMany() && !$link.isCardinalityOneToMany() )
${entity.name.toLowerCase()}.${link.formatedName(0)}=${link.targetEntityType}
#end
#end
${entity.name.toLowerCase()}.error.delete=Erreur lors de la suppression de ${entity.name} : {0} {1}
${entity.name.toLowerCase()}.error.update=Erreur lors de la mise \u00e0 jour de ${entity.name} : {0} {1}
${entity.name.toLowerCase()}.error.create=Erreur lors de la cr\u00e9ation de ${entity.name} : {0} {1}
#end

#exception
exception_message=Exception Message
exception_stacktrace=Exception Stack Trace
exception_cookie=Cookies
exception_details=Details

#dataAccessFailure_jspx
error_dataaccessfailure_title=Data access failure
error_dataaccessfailure_problemdescription=Sorry, a problem occurred while accessing the database.

#resourceNotFound_jspx
error_resourcenotfound_title=Requested Resource Not Found
error_resourcenotfound_problemdescription=Sorry, we did not find the resource you were looking for.

#uncaughtException_jspx
error_uncaughtexception_title=Internal Error
error_uncaughtexception_problemdescription=Sorry, we encountered an internal error.
